FROM alpine:latest
RUN apk add --no-cache iproute2

COPY build/node /app
COPY docker/entrypoint-fast /usr/bin/entrypoint-builtin

WORKDIR /cometbft
VOLUME /cometbft
ENV CMTHOME=/cometbft
ENV GORACE="halt_on_error=1"

# Accept MEMPOOL_THRESHOLD_PERCENT from build arguments
ARG MEMPOOL_THRESHOLD_PERCENT
ENV MEMPOOL_THRESHOLD_PERCENT=${MEMPOOL_THRESHOLD_PERCENT}

EXPOSE 26656 26657 26660 6060
ENTRYPOINT ["/usr/bin/entrypoint-builtin"]
STOPSIGNAL SIGTERM
